In [2]:
import numpy as np

In [3]:
na = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(na, na.shape)
type(na)

[1 2 3 4 5 6 7 8] (8,)


numpy.ndarray

In [4]:
na = np.array([[1], [2], [3], [4], [5]])
print(na, na.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [5]:
c = np.array([[1, 2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

### custom arrays

In [6]:
z = np.zeros((3, 3), dtype=int)
print(z)

o = np.ones((2, 3))
print(o)

f = np.full((2, 4), 7)
print(f)

h = np.eye(3, 3)
h

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random matrix

In [7]:
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0.29432964 0.50566242 0.63913538]
 [0.32273276 0.23306311 0.87291091]]


In [8]:
# [rows,colms]
randomMatrix[:, 1]

array([0.50566242, 0.23306311])

In [9]:
randomMatrix[1, 1:]

array([0.23306311, 0.87291091])

In [10]:
z[1,] = 4
z

array([[0, 0, 0],
       [4, 4, 4],
       [0, 0, 0]])

In [11]:
z[:, 2] = 1

In [12]:
print(type(z))

<class 'numpy.ndarray'>


In [13]:
z.dtype

dtype('int32')

## Mathematical Operations

In [14]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
x, y = np.array(A), np.array(B)
# A+B
print(x + y)

[[ 6  8]
 [10 12]]


In [15]:
print(np.add(x, y))  # print(x + y)
print()
print(np.subtract(x, y))  # print(x - y)
print()
print(np.multiply(x, y))  # print(x * y)
print()
print(np.divide(x, y))  # print(x / y)
print(x // y)
print(y // x)

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0 0]
 [0 0]]
[[5 3]
 [2 2]]


In [16]:
print(np.dot(x, y))  # print(x.dot(y))

[[19 22]
 [43 50]]


In [40]:
a, b = np.array([1, 2, 3]), np.array([1, 2, 3])
print(a.dot(b))

14


In [18]:
x = [[1, 2], [3, 4]]
print(np.sum(x))
print(np.sum(x, axis=1))

10
[3 7]


In [19]:
print(a)
print(a**2)

[1 2 3]
[1 4 9]


In [41]:
a = np.stack((a, b), axis=0)
a

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
# reshape
a.reshape((3, 2))

array([[1, 2],
       [3, 1],
       [2, 3]])

In [52]:
print(a.reshape((-1, 3)))  # if you do not know no of rows
a.reshape((6, -1))  # if you do not know no of columns

[[1 2 3]
 [1 2 3]]


array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

## Numpy Random

In [59]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
np.random.seed(1)
np.random.shuffle(a)
a

array([3, 5, 6, 0, 8, 2, 1, 9, 7, 4])

In [62]:
x = np.random.rand(2, 3)
x

array([[0.14868201, 0.18386813, 0.7491463 ],
       [0.32291049, 0.4954441 , 0.3908385 ]])

In [68]:
x = np.random.randint(1, 10, (2, 3))
x

array([[5, 9, 3],
       [8, 2, 1]])

In [98]:
ch = ["shinra", "makise", "sister", "hinawa", "pracharak"]
np.random.choice(ch)

'hinawa'

## Statastics functions

In [260]:
data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [268]:
print(np.min(data))
print(np.min(data, axis=0))
print(np.min(data, axis=1))

1
[1 2 3 4 5]
[1 6]
[1 2 3 4 5]


In [275]:
print(np.mean(data[0]))
print(np.mean(data, axis=0))
print(np.mean(data, axis=1))

3.0
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]
